---
- name: Set OS dependent variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    ansible_distribution_lts_offset: >-
      {{
        ansible_facts['distribution_major_version']|int % 2
        if ansible_facts['distribution'] == "Ubuntu"
        else 0
      }}
    ansible_distribution_lts_version: >-
      {{
        ansible_facts['distribution_major_version']|int -
        ansible_distribution_lts_offset|int
        if ansible_facts['distribution'] == "Ubuntu"
        else ansible_facts['distribution_version']
      }}
    params:
      files:
        - "{{ ansible_facts['distribution'] }}_{{ ansible_distribution_lts_version }}.yml"
        - "{{ ansible_facts['os_family'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"
        - "{{ playbook_dir }}/vars"
